version: '2'
services:
    hshbapi-app:
        image: hshbapi
        external_links:
            - hshbapi-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hshbapi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    hshbapi-mysql:
        extends:
            file: mysql.yml
            service: hshbapi-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
